---
# Variable configuration.
- name: Include variable configuration
  ansible.builtin.include_tasks: variables.yml

# Setup/install tasks.
- name: Setup for ArchLinux
  ansible.builtin.include_tasks: setup-archlinux.yml
  when: ansible_os_family == 'ArchLinux'

- name: Setup for Debian
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Setup for RedHat
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Initialize configuration
  ansible.builtin.include_tasks: initialize.yml

- name: Apply configuration
  ansible.builtin.include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- name: Import user configuration
  ansible.builtin.import_tasks: users.yml

- name: Import database configuration
  ansible.builtin.import_tasks: databases.yml

- name: Import user properties configuration
  ansible.builtin.import_tasks: users_props.yml
